import React, { PropTypes } from 'react';
import Markdown from 'react-markdownit';

/** a table view for the props metadata of a react component generated by
 * react-docgen (loaded by react-docgen-loader with webpack) */
 const PropsTable = ({ className, propMetaData, ...customProps }) => {
  if (className) className += ' component-props-table';
  return (
    <div className='markdown-body'>
      <table className={className} src={'some list'} {...customProps}>
      <thead>
      <tr>
        <th>Prop Name</th>
        <th>Type</th>
        <th>Is Required</th>
        <th>Default Value</th>
        <th>Description</th>
      </tr>
      </thead>
      <tbody>
      {Object.keys(propMetaData).map((key)=> {
        var prop = propMetaData[key];
        return (
          <tr key={key}>
            <td style={{color: 'rgb(17, 147, 154)'}}>{key}</td>
            <td>{(prop.type ? prop.type.name : '')}</td>
            {(prop.required ?
              <td style={{color: 'rgb(255, 76, 34)'}}>required</td>
              : <td style={{color: '#c6c6c6'}}>optional</td>)}
            {(prop.defaultValue ?
              <td style={{color: 'rgb(236, 171, 32)'}}>{prop.defaultValue.value}</td>
              : <td style={{color: '#c6c6c6'}}>none</td>)}
            <Markdown tagName='td'>{prop.description}</Markdown>
          </tr>
        );
      })}
      </tbody>
    </table>
    </div>
  )
};

const { object } = PropTypes;

PropsTable.propTypes = {
  /** this is the `metadata.props` field of what metadata you get from the react-docgen-loader.  */
  propMetaData: object
};

PropsTable.defaultProps = {
  propMetaData: {}
};

export default PropsTable;
